<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-T8B8QGB" failures="1" tests="5" name="Personal Loan" time="0.207" errors="0" timestamp="2022-08-30T00:40:42 IST">
  <testcase classname="TestNGPackage.day1" name="Demo" time="0.048">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNGPackage.day1.Demo(day1.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="TestNGPackage.day2" name="ploan" time="0.005"/>
  <testcase classname="TestNGPackage.day4" name="LoginAPIHomeLoan" time="0.003"/>
  <testcase classname="TestNGPackage.day4" name="MobileLoginHomeLoan" time="0.006"/>
  <testcase classname="TestNGPackage.day4" name="WebLoginHomeLoan" time="0.002"/>
  <testcase classname="TestNGPackage.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
